"""Git pre-push hook installer for contagious_scan.

Writes and activates a ``pre-push`` hook script into ``.git/hooks/`` of a
target Git repository.  When installed, the hook runs
``contagious-scan scan`` on the repository before each ``git push`` and
blocks the push if critical-severity findings are detected.

The installer can also manage (remove / check) existing hook installations.

Typical usage::

    from contagious_scan.hook_installer import HookInstaller

    installer = HookInstaller(repo_path=".", ci_override=False)
    installer.install()
    print(installer.is_installed())
    installer.uninstall()
"""

from __future__ import annotations

import logging
import os
import stat
from pathlib import Path
from typing import NamedTuple

try:
    from git import InvalidGitRepositoryError, NoSuchPathError, Repo
except ImportError as exc:  # pragma: no cover
    raise ImportError(
        "GitPython is required. Install it with: pip install gitpython"
    ) from exc

logger = logging.getLogger(__name__)

# Marker written into the hook file so we can identify our own installations
_HOOK_MARKER: str = "# contagious_scan managed hook"

# Default minimum severity for the pre-push hook
_DEFAULT_MIN_SEVERITY: str = "critical"


# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------


class HookInstallerError(Exception):
    """Base exception for hook installer errors."""


class NotAGitRepoError(HookInstallerError):
    """Raised when the target path is not a Git repository."""


class HookAlreadyInstalledError(HookInstallerError):
    """Raised when a hook is already installed and ``force=False``."""


class ExistingHookError(HookInstallerError):
    """Raised when a non-contagious_scan hook already exists and ``force=False``."""


# ---------------------------------------------------------------------------
# Hook script templates
# ---------------------------------------------------------------------------

_HOOK_TEMPLATE_NORMAL: str = """\
#!/usr/bin/env bash
{marker}
# Blocks pushes when critical-severity indicators are detected.
# Generated by contagious_scan {version}
# Remove this file or run 'contagious-scan install-hook --uninstall' to disable.
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"

if ! command -v contagious-scan &>/dev/null; then
    echo "[contagious_scan] WARNING: contagious-scan not found in PATH. Skipping scan."
    exit 0
fi

echo "[contagious_scan] Scanning staged files before push..."
contagious-scan scan "$REPO_ROOT" --staged-only --min-severity {min_severity} --format plain
EXIT_CODE=$?

if [ "$EXIT_CODE" -eq 1 ]; then
    echo ""
    echo "[contagious_scan] \u274c {min_severity_upper} findings detected. Push BLOCKED."
    echo "[contagious_scan] Run 'contagious-scan scan . --format rich' for details."
    echo "[contagious_scan] Fix the issues or use --ci-override to bypass (CI only)."
    exit 1
elif [ "$EXIT_CODE" -eq 2 ]; then
    echo "[contagious_scan] WARNING: Scan error encountered. Push allowed (fail-open)."
    exit 0
fi

echo "[contagious_scan] \u2705 No {min_severity_upper} findings detected. Push allowed."
exit 0
"""

_HOOK_TEMPLATE_CI_OVERRIDE: str = """\
#!/usr/bin/env bash
{marker}
# CI override mode: scan runs but findings do NOT block the push.
# Generated by contagious_scan {version}
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"

if ! command -v contagious-scan &>/dev/null; then
    echo "[contagious_scan] WARNING: contagious-scan not found in PATH. Skipping scan."
    exit 0
fi

echo "[contagious_scan] Scanning staged files (CI override — non-blocking)..."
contagious-scan scan "$REPO_ROOT" --staged-only --min-severity {min_severity} \\
    --format plain --ci-override || true
echo "[contagious_scan] Scan complete (CI override active — push not blocked)."
exit 0
"""


# ---------------------------------------------------------------------------
# InstallResult
# ---------------------------------------------------------------------------


class InstallResult(NamedTuple):
    """Result of a hook installation or management operation.

    Attributes
    ----------
    success:
        ``True`` if the operation completed without errors.
    hook_path:
        Path of the hook file that was written / checked / removed.
    message:
        Human-readable status message.
    """

    success: bool
    hook_path: Path
    message: str


# ---------------------------------------------------------------------------
# HookInstaller
# ---------------------------------------------------------------------------


class HookInstaller:
    """Manages the contagious_scan Git pre-push hook.

    Parameters
    ----------
    repo_path:
        Path to the Git repository root (or any subdirectory).
    ci_override:
        If ``True``, the installed hook will run in non-blocking mode,
        reporting findings without blocking the push.
    min_severity:
        Minimum severity level that triggers a blocked push.
        Defaults to ``"critical"``.

    Examples
    --------
    ::

        installer = HookInstaller("/path/to/repo")
        result = installer.install(force=True)
        print(result.message)
    """

    def __init__(
        self,
        repo_path: str | Path,
        ci_override: bool = False,
        min_severity: str = _DEFAULT_MIN_SEVERITY,
    ) -> None:
        self._repo_path = Path(repo_path)
        self._ci_override = ci_override
        self._min_severity = min_severity.lower()
        self._repo = self._open_repo()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    @property
    def hooks_dir(self) -> Path:
        """Absolute path to the ``.git/hooks`` directory."""
        return Path(self._repo.git_dir) / "hooks"

    @property
    def hook_path(self) -> Path:
        """Absolute path to the ``pre-push`` hook file."""
        return self.hooks_dir / "pre-push"

    def is_installed(self) -> bool:
        """Return ``True`` if a contagious_scan hook is currently installed.

        Returns
        -------
        bool
            ``True`` if the hook file exists and contains the contagious_scan
            marker comment.
        """
        if not self.hook_path.exists():
            return False
        try:
            content = self.hook_path.read_text(encoding="utf-8")
            return _HOOK_MARKER in content
        except OSError:
            return False

    def has_existing_hook(self) -> bool:
        """Return ``True`` if a *non-contagious_scan* hook file exists.

        Returns
        -------
        bool
            ``True`` if the hook file exists but was NOT installed by us.
        """
        if not self.hook_path.exists():
            return False
        return not self.is_installed()

    def install(
        self,
        force: bool = False,
        backup: bool = True,
    ) -> InstallResult:
        """Write and activate the pre-push hook script.

        Parameters
        ----------
        force:
            If ``True``, overwrite any existing hook (including non-ours).
            If ``False`` and a non-contagious_scan hook exists, raise
            :class:`ExistingHookError`.
        backup:
            If ``True`` and an existing hook is being overwritten, save a
            ``.bak`` copy first.

        Returns
        -------
        InstallResult
            Result of the installation.

        Raises
        ------
        ExistingHookError
            If an unrecognised hook exists and ``force=False``.
        HookInstalledError
            If our own hook is already installed and ``force=False``.
        HookInstallerError
            For unexpected I/O or permission errors.
        """
        # Check for pre-existing hooks
        if self.is_installed() and not force:
            return InstallResult(
                success=False,
                hook_path=self.hook_path,
                message=(
                    f"contagious_scan hook is already installed at "
                    f"'{self.hook_path}'. Use force=True to reinstall."
                ),
            )

        if self.has_existing_hook() and not force:
            raise ExistingHookError(
                f"A non-contagious_scan pre-push hook already exists at "
                f"'{self.hook_path}'. Use force=True to overwrite it."
            )

        # Backup existing hook if requested
        if self.hook_path.exists() and backup:
            bak_path = self.hook_path.with_suffix(".bak")
            try:
                import shutil
                shutil.copy2(str(self.hook_path), str(bak_path))
                logger.info("Backed up existing hook to '%s'", bak_path)
            except OSError as exc:
                logger.warning("Could not back up existing hook: %s", exc)

        # Ensure hooks directory exists
        try:
            self.hooks_dir.mkdir(parents=True, exist_ok=True)
        except OSError as exc:
            raise HookInstallerError(
                f"Cannot create hooks directory '{self.hooks_dir}': {exc}"
            ) from exc

        # Render the hook script
        script = self._render_hook_script()

        # Write the hook file
        try:
            self.hook_path.write_text(script, encoding="utf-8")
        except OSError as exc:
            raise HookInstallerError(
                f"Cannot write hook file '{self.hook_path}': {exc}"
            ) from exc

        # Make executable
        self._make_executable(self.hook_path)

        mode_str = "CI-override (non-blocking)" if self._ci_override else "blocking"
        msg = (
            f"✅ pre-push hook installed at '{self.hook_path}' "
            f"[mode: {mode_str}, min-severity: {self._min_severity}]"
        )
        logger.info(msg)
        return InstallResult(success=True, hook_path=self.hook_path, message=msg)

    def uninstall(self) -> InstallResult:
        """Remove the contagious_scan pre-push hook.

        If the hook was installed with a backup, the backup is NOT
        automatically restored (to avoid silently re-activating third-party
        hooks).  Users should manually restore backups if needed.

        Returns
        -------
        InstallResult
            Result of the uninstall operation.

        Raises
        ------
        HookInstallerError
            If the hook file cannot be removed.
        """
        if not self.hook_path.exists():
            return InstallResult(
                success=True,
                hook_path=self.hook_path,
                message="No pre-push hook found. Nothing to uninstall.",
            )

        if not self.is_installed():
            return InstallResult(
                success=False,
                hook_path=self.hook_path,
                message=(
                    f"The hook at '{self.hook_path}' was not installed by "
                    "contagious_scan. Refusing to remove it automatically."
                ),
            )

        try:
            self.hook_path.unlink()
        except OSError as exc:
            raise HookInstallerError(
                f"Cannot remove hook file '{self.hook_path}': {exc}"
            ) from exc

        msg = f"🗑 pre-push hook removed from '{self.hook_path}'."
        logger.info(msg)
        return InstallResult(success=True, hook_path=self.hook_path, message=msg)

    def status(self) -> dict[str, object]:
        """Return a dictionary describing the current hook installation status.

        Returns
        -------
        dict[str, object]
            Keys: ``installed``, ``hook_path``, ``ci_override``, ``min_severity``,
            ``hooks_dir_exists``, ``hook_executable``, ``our_hook``.
        """
        installed = self.is_installed()
        hook_exists = self.hook_path.exists()
        is_executable = False
        our_hook = installed

        if hook_exists:
            try:
                mode = os.stat(str(self.hook_path)).st_mode
                is_executable = bool(mode & (stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH))
            except OSError:
                pass

        return {
            "installed": installed,
            "hook_path": str(self.hook_path),
            "hooks_dir_exists": self.hooks_dir.exists(),
            "hook_file_exists": hook_exists,
            "hook_executable": is_executable,
            "our_hook": our_hook,
            "ci_override": self._ci_override,
            "min_severity": self._min_severity,
            "repo_path": str(self._repo_path.resolve()),
        }

    def get_hook_content(self) -> str | None:
        """Return the current content of the pre-push hook file.

        Returns
        -------
        str or None
            The hook script content, or ``None`` if no hook file exists.
        """
        if not self.hook_path.exists():
            return None
        try:
            return self.hook_path.read_text(encoding="utf-8")
        except OSError:
            return None

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _open_repo(self) -> Repo:
        """Open the Git repository at the configured path.

        Returns
        -------
        git.Repo
            Opened repository.

        Raises
        ------
        NotAGitRepoError
            If the path is not within a Git repository.
        """
        try:
            return Repo(str(self._repo_path), search_parent_directories=True)
        except (InvalidGitRepositoryError, NoSuchPathError) as exc:
            raise NotAGitRepoError(
                f"'{self._repo_path}' is not a valid Git repository: {exc}"
            ) from exc

    def _render_hook_script(self) -> str:
        """Render the hook shell script with the current configuration.

        Returns
        -------
        str
            Complete bash hook script.
        """
        from contagious_scan import __version__

        template = (
            _HOOK_TEMPLATE_CI_OVERRIDE
            if self._ci_override
            else _HOOK_TEMPLATE_NORMAL
        )
        return template.format(
            marker=_HOOK_MARKER,
            version=__version__,
            min_severity=self._min_severity,
            min_severity_upper=self._min_severity.upper(),
        )

    @staticmethod
    def _make_executable(path: Path) -> None:
        """Add executable bits to *path* (user, group, other).

        Parameters
        ----------
        path:
            File to make executable.

        Raises
        ------
        HookInstallerError
            If the chmod operation fails.
        """
        try:
            current_mode = os.stat(str(path)).st_mode
            new_mode = current_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH
            os.chmod(str(path), new_mode)
        except OSError as exc:
            raise HookInstallerError(
                f"Cannot make '{path}' executable: {exc}"
            ) from exc


# ---------------------------------------------------------------------------
# Module-level convenience functions
# ---------------------------------------------------------------------------


def install_hook(
    repo_path: str | Path,
    ci_override: bool = False,
    min_severity: str = _DEFAULT_MIN_SEVERITY,
    force: bool = False,
    backup: bool = True,
) -> InstallResult:
    """Install the contagious_scan pre-push hook into a repository.

    Parameters
    ----------
    repo_path:
        Path to the Git repository.
    ci_override:
        If ``True``, install in non-blocking CI mode.
    min_severity:
        Minimum severity level that triggers a blocked push.
    force:
        If ``True``, overwrite any existing hook.
    backup:
        If ``True``, back up any existing hook before overwriting.

    Returns
    -------
    InstallResult
        Result of the installation.

    Raises
    ------
    NotAGitRepoError
        If *repo_path* is not a valid Git repository.
    ExistingHookError
        If a non-contagious_scan hook exists and ``force=False``.
    HookInstallerError
        For I/O or permission errors.
    """
    installer = HookInstaller(
        repo_path=repo_path,
        ci_override=ci_override,
        min_severity=min_severity,
    )
    return installer.install(force=force, backup=backup)


def uninstall_hook(repo_path: str | Path) -> InstallResult:
    """Remove the contagious_scan pre-push hook from a repository.

    Parameters
    ----------
    repo_path:
        Path to the Git repository.

    Returns
    -------
    InstallResult
        Result of the uninstall operation.

    Raises
    ------
    NotAGitRepoError
        If *repo_path* is not a valid Git repository.
    HookInstallerError
        If the hook file cannot be removed.
    """
    installer = HookInstaller(repo_path=repo_path)
    return installer.uninstall()


def is_hook_installed(repo_path: str | Path) -> bool:
    """Return ``True`` if a contagious_scan hook is installed in *repo_path*.

    Parameters
    ----------
    repo_path:
        Path to the Git repository.

    Returns
    -------
    bool
        ``True`` if the hook is installed.

    Raises
    ------
    NotAGitRepoError
        If *repo_path* is not a valid Git repository.
    """
    installer = HookInstaller(repo_path=repo_path)
    return installer.is_installed()


def get_hook_status(repo_path: str | Path) -> dict[str, object]:
    """Return a status dictionary for the hook installation in *repo_path*.

    Parameters
    ----------
    repo_path:
        Path to the Git repository.

    Returns
    -------
    dict[str, object]
        Status information dictionary.

    Raises
    ------
    NotAGitRepoError
        If *repo_path* is not a valid Git repository.
    """
    installer = HookInstaller(repo_path=repo_path)
    return installer.status()
